### ISSUE TITLE
Add Jenkins support

### ISSUE THREAD

**Issue by ksindi** [jwplayer/buildpipe-buildkite-plugin#11]
Would be interesting to generalize the repo to other CIs that support dynamic pipelines. There's a way to do it in Jenkins using a Jenkinsfile.

Some resources that might be useful:
  - https://jenkins.io/doc/book/pipeline/
  - https://stackoverflow.com/questions/45711473/how-to-load-dynamic-jenkinsfile-during-a-build
  - https://jenkins.io/blog/2017/09/25/declarative-1/
  - https://github.com/jenkinsci/pipeline-examples/blob/master/docs/BEST_PRACTICES.md
  - https://support.cloudbees.com/hc/en-us/articles/226122247-How-to-Customize-Checkout-for-Pipeline-Multibranch-

**Comment by kevinlu1211** [comment]
This is very interesting would you be willing to provide a high level description of how to implement it so that I can have a go at it? I have a rough idea of how to do it though, it seems like you are much more experienced.

**Comment by ksindi** [comment]
@kevinlu1211 the idea would be to dynamically create the Jenkinsfile and load it as shown here: https://stackoverflow.com/questions/45711473/how-to-load-dynamic-jenkinsfile-during-a-build. 

So instead of the steps being rendered in yaml for Buildkite, you would have buildpipe to render it in Groovy.

So it would look something like
```
pipeline { 
    agent any 
    stages {
        stage('build') { 
            steps { 
                sh 'make build' 
            }
        }
        stage('test'){
            steps {
                sh 'make test'
            }
        }
        stage('deploy') {
            steps {
                sh 'make deploy'
            }
        }
    }
}
```

Essentially what you would need to change is `generate_project_steps` and `generate_stair_steps` in https://github.com/ksindi/buildpipe/blob/master/buildpipe/pipeline.py. You would probably have to using a templating language like Jinja2 to do that. This block https://github.com/ksindi/buildpipe/blob/master/buildpipe/pipeline.py#L192-L199 would also have to change.

Feel free to make a PR that POCs Jenkins and I can refactor it to support both Buildkite and Jenkins.
