### ISSUE TITLE
Did you forget to release v0.9.2?

### ISSUE THREAD

**Issue by tskardal** [jwplayer/buildpipe-buildkite-plugin#75]
Using the details from README I tried to use the plugin v0.9.2. This doesn't work as [this command](https://github.com/jwplayer/buildpipe-buildkite-plugin/blob/master/hooks/command#L8) fails because v0.9.2 is only tagged and not yet released. 

The binary asset being downloaded by the plugin does not exist and gives 404. 😅 

https://github.com/jwplayer/buildpipe-buildkite-plugin/releases/download/v0.9.2/buildpipe-linux

**Comment by boyntoni** [comment]
@tskardal First, sorry for the lack of response, I've updated my notification settings to be sure I don't miss any more.

This was an oversight; I've gone ahead and released `v0.9.2`. Thanks for opening this issue.
