### ISSUE TITLE
Allow manual build of specific project label/path without code push

### ISSUE THREAD

**Issue by karlkatzke** [jwplayer/buildpipe-buildkite-plugin#78]
Unless I'm missing something (and that's really possible), it's impossible to trigger a build without a code change that flags which paths/labels to build. (There was a pull request - #13 - when this project was still in Python to that regard, and it looks like it was merged, so this may be a regression.) 

Use case: Our Ansible roles are in a monorepo. We would like to trigger a Packer run for two of those roles weekly so that we pick up changes to packages upstream from us. To do that, we'd need to be able to add to the project paths that will be built by getAffectedProjects. 

This feature is similar to #74 .

**Comment by boyntoni** [comment]
@karlkatzke Thanks for the feature request, this is something that we have also wanted here at JW Player. This should be available in the coming days.

**Comment by boyntoni** [comment]
@karlkatzke Sorry for delay, this feature is available in v0.10.0. Thanks again for the suggestion!

**Comment by karlkatzke** [comment]
Thanks, saw that yesterday! Much appreciated!
